2023-12-15T00:23:50.774119307Z stderr F I1215 00:23:50.773861       1 server_others.go:69] "Using iptables proxy"
2023-12-15T00:23:50.877300854Z stderr F I1215 00:23:50.877122       1 node.go:141] Successfully retrieved node IP: 10.140.0.139
2023-12-15T00:23:50.894854129Z stderr F I1215 00:23:50.894742       1 conntrack.go:100] "Set sysctl" entry="net/netfilter/nf_conntrack_max" value=1310720
2023-12-15T00:23:50.894873447Z stderr F I1215 00:23:50.894791       1 conntrack.go:52] "Setting nf_conntrack_max" nfConntrackMax=1310720
2023-12-15T00:23:51.01761659Z stderr F I1215 00:23:51.017503       1 conntrack.go:83] "Setting conntrack hashsize" conntrackHashsize=327680
2023-12-15T00:23:51.049749583Z stderr F I1215 00:23:51.049631       1 conntrack.go:100] "Set sysctl" entry="net/netfilter/nf_conntrack_tcp_timeout_close_wait" value=3600
2023-12-15T00:23:51.393570265Z stderr F I1215 00:23:51.393435       1 server.go:632] "kube-proxy running in dual-stack mode" primary ipFamily="IPv4"
2023-12-15T00:23:51.39638128Z stderr F I1215 00:23:51.396274       1 server_others.go:152] "Using iptables Proxier"
2023-12-15T00:23:51.396407906Z stderr F I1215 00:23:51.396327       1 server_others.go:421] "Detect-local-mode set to ClusterCIDR, but no cluster CIDR for family" ipFamily="IPv6"
2023-12-15T00:23:51.396444709Z stderr F I1215 00:23:51.396341       1 server_others.go:438] "Defaulting to no-op detect-local"
2023-12-15T00:23:51.396465011Z stderr F I1215 00:23:51.396373       1 proxier.go:251] "Setting route_localnet=1 to allow node-ports on localhost; to change this either disable iptables.localhostNodePorts (--iptables-localhost-nodeports) or set nodePortAddresses (--nodeport-addresses) to filter loopback addresses"
2023-12-15T00:23:51.39686412Z stderr F I1215 00:23:51.396763       1 server.go:846] "Version info" version="v1.28.4"
2023-12-15T00:23:51.396876334Z stderr F I1215 00:23:51.396785       1 server.go:848] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
2023-12-15T00:23:51.398327731Z stderr F I1215 00:23:51.398169       1 config.go:97] "Starting endpoint slice config controller"
2023-12-15T00:23:51.398351503Z stderr F I1215 00:23:51.398216       1 shared_informer.go:311] Waiting for caches to sync for endpoint slice config
2023-12-15T00:23:51.398359026Z stderr F I1215 00:23:51.398226       1 config.go:188] "Starting service config controller"
2023-12-15T00:23:51.398366068Z stderr F I1215 00:23:51.398229       1 config.go:315] "Starting node config controller"
2023-12-15T00:23:51.398372704Z stderr F I1215 00:23:51.398244       1 shared_informer.go:311] Waiting for caches to sync for service config
2023-12-15T00:23:51.398379003Z stderr F I1215 00:23:51.398254       1 shared_informer.go:311] Waiting for caches to sync for node config
2023-12-15T00:23:51.499368922Z stderr F I1215 00:23:51.499204       1 shared_informer.go:318] Caches are synced for node config
2023-12-15T00:23:51.499401909Z stderr F I1215 00:23:51.499244       1 shared_informer.go:318] Caches are synced for endpoint slice config
2023-12-15T00:23:51.499428768Z stderr F I1215 00:23:51.499309       1 shared_informer.go:318] Caches are synced for service config
2024-03-15T18:36:41.868509627Z stderr F W0315 18:36:41.868282       1 reflector.go:458] vendor/k8s.io/client-go/informers/factory.go:150: watch of *v1.EndpointSlice ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
2024-03-15T18:36:41.868554306Z stderr F W0315 18:36:41.868311       1 reflector.go:458] vendor/k8s.io/client-go/informers/factory.go:150: watch of *v1.Node ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
2024-03-15T18:36:41.868564397Z stderr F W0315 18:36:41.868225       1 reflector.go:458] vendor/k8s.io/client-go/informers/factory.go:150: watch of *v1.Service ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
2024-03-15T18:36:43.076653484Z stderr F W0315 18:36:43.076367       1 reflector.go:535] vendor/k8s.io/client-go/informers/factory.go:150: failed to list *v1.EndpointSlice: Get "https://10.140.0.139:6443/apis/discovery.k8s.io/v1/endpointslices?labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=12829679": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:36:43.076689455Z stderr F E0315 18:36:43.076481       1 reflector.go:147] vendor/k8s.io/client-go/informers/factory.go:150: Failed to watch *v1.EndpointSlice: failed to list *v1.EndpointSlice: Get "https://10.140.0.139:6443/apis/discovery.k8s.io/v1/endpointslices?labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=12829679": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:36:43.374871822Z stderr F W0315 18:36:43.374692       1 reflector.go:535] vendor/k8s.io/client-go/informers/factory.go:150: failed to list *v1.Service: Get "https://10.140.0.139:6443/api/v1/services?labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=12829624": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:36:43.374921802Z stderr F E0315 18:36:43.374765       1 reflector.go:147] vendor/k8s.io/client-go/informers/factory.go:150: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://10.140.0.139:6443/api/v1/services?labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=12829624": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:36:43.418109759Z stderr F W0315 18:36:43.417925       1 reflector.go:535] vendor/k8s.io/client-go/informers/factory.go:150: failed to list *v1.Node: Get "https://10.140.0.139:6443/api/v1/nodes?fieldSelector=metadata.name%3Ds141&resourceVersion=12829658": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:36:43.461997035Z stderr F E0315 18:36:43.417998       1 reflector.go:147] vendor/k8s.io/client-go/informers/factory.go:150: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://10.140.0.139:6443/api/v1/nodes?fieldSelector=metadata.name%3Ds141&resourceVersion=12829658": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:36:44.902011706Z stderr F W0315 18:36:44.901792       1 reflector.go:535] vendor/k8s.io/client-go/informers/factory.go:150: failed to list *v1.EndpointSlice: Get "https://10.140.0.139:6443/apis/discovery.k8s.io/v1/endpointslices?labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=12829679": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:36:44.902054028Z stderr F E0315 18:36:44.901868       1 reflector.go:147] vendor/k8s.io/client-go/informers/factory.go:150: Failed to watch *v1.EndpointSlice: failed to list *v1.EndpointSlice: Get "https://10.140.0.139:6443/apis/discovery.k8s.io/v1/endpointslices?labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=12829679": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:36:45.406227873Z stderr F W0315 18:36:45.405991       1 reflector.go:535] vendor/k8s.io/client-go/informers/factory.go:150: failed to list *v1.Node: Get "https://10.140.0.139:6443/api/v1/nodes?fieldSelector=metadata.name%3Ds141&resourceVersion=12829658": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:36:45.406268275Z stderr F E0315 18:36:45.406063       1 reflector.go:147] vendor/k8s.io/client-go/informers/factory.go:150: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://10.140.0.139:6443/api/v1/nodes?fieldSelector=metadata.name%3Ds141&resourceVersion=12829658": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:36:46.009261036Z stderr F W0315 18:36:46.009020       1 reflector.go:535] vendor/k8s.io/client-go/informers/factory.go:150: failed to list *v1.Service: Get "https://10.140.0.139:6443/api/v1/services?labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=12829624": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:36:46.009351725Z stderr F E0315 18:36:46.009114       1 reflector.go:147] vendor/k8s.io/client-go/informers/factory.go:150: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://10.140.0.139:6443/api/v1/services?labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=12829624": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:36:49.820301625Z stderr F W0315 18:36:49.820050       1 reflector.go:535] vendor/k8s.io/client-go/informers/factory.go:150: failed to list *v1.Node: Get "https://10.140.0.139:6443/api/v1/nodes?fieldSelector=metadata.name%3Ds141&resourceVersion=12829658": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:36:49.820338745Z stderr F E0315 18:36:49.820148       1 reflector.go:147] vendor/k8s.io/client-go/informers/factory.go:150: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://10.140.0.139:6443/api/v1/nodes?fieldSelector=metadata.name%3Ds141&resourceVersion=12829658": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:36:50.22084442Z stderr F W0315 18:36:50.220645       1 reflector.go:535] vendor/k8s.io/client-go/informers/factory.go:150: failed to list *v1.EndpointSlice: Get "https://10.140.0.139:6443/apis/discovery.k8s.io/v1/endpointslices?labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=12829679": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:36:50.22087478Z stderr F E0315 18:36:50.220703       1 reflector.go:147] vendor/k8s.io/client-go/informers/factory.go:150: Failed to watch *v1.EndpointSlice: failed to list *v1.EndpointSlice: Get "https://10.140.0.139:6443/apis/discovery.k8s.io/v1/endpointslices?labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=12829679": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:36:50.685809538Z stderr F W0315 18:36:50.685534       1 reflector.go:535] vendor/k8s.io/client-go/informers/factory.go:150: failed to list *v1.Service: Get "https://10.140.0.139:6443/api/v1/services?labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=12829624": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:36:50.685862753Z stderr F E0315 18:36:50.685631       1 reflector.go:147] vendor/k8s.io/client-go/informers/factory.go:150: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://10.140.0.139:6443/api/v1/services?labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=12829624": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:36:56.617742188Z stderr F W0315 18:36:56.617502       1 reflector.go:535] vendor/k8s.io/client-go/informers/factory.go:150: failed to list *v1.Node: Get "https://10.140.0.139:6443/api/v1/nodes?fieldSelector=metadata.name%3Ds141&resourceVersion=12829658": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:36:56.617779731Z stderr F E0315 18:36:56.617569       1 reflector.go:147] vendor/k8s.io/client-go/informers/factory.go:150: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://10.140.0.139:6443/api/v1/nodes?fieldSelector=metadata.name%3Ds141&resourceVersion=12829658": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:36:56.981229258Z stderr F W0315 18:36:56.981074       1 reflector.go:535] vendor/k8s.io/client-go/informers/factory.go:150: failed to list *v1.EndpointSlice: Get "https://10.140.0.139:6443/apis/discovery.k8s.io/v1/endpointslices?labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=12829679": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:36:56.981288633Z stderr F E0315 18:36:56.981150       1 reflector.go:147] vendor/k8s.io/client-go/informers/factory.go:150: Failed to watch *v1.EndpointSlice: failed to list *v1.EndpointSlice: Get "https://10.140.0.139:6443/apis/discovery.k8s.io/v1/endpointslices?labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=12829679": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:36:59.83646974Z stderr F W0315 18:36:59.836192       1 reflector.go:535] vendor/k8s.io/client-go/informers/factory.go:150: failed to list *v1.Service: Get "https://10.140.0.139:6443/api/v1/services?labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=12829624": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:36:59.836512235Z stderr F E0315 18:36:59.836264       1 reflector.go:147] vendor/k8s.io/client-go/informers/factory.go:150: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://10.140.0.139:6443/api/v1/services?labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=12829624": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:37:20.384982378Z stderr F W0315 18:37:20.384682       1 reflector.go:535] vendor/k8s.io/client-go/informers/factory.go:150: failed to list *v1.Node: Get "https://10.140.0.139:6443/api/v1/nodes?fieldSelector=metadata.name%3Ds141&resourceVersion=12829658": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:37:20.385032069Z stderr F E0315 18:37:20.384781       1 reflector.go:147] vendor/k8s.io/client-go/informers/factory.go:150: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://10.140.0.139:6443/api/v1/nodes?fieldSelector=metadata.name%3Ds141&resourceVersion=12829658": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:37:21.777599797Z stderr F W0315 18:37:21.777404       1 reflector.go:535] vendor/k8s.io/client-go/informers/factory.go:150: failed to list *v1.Service: Get "https://10.140.0.139:6443/api/v1/services?labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=12829624": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:37:21.777641535Z stderr F E0315 18:37:21.777497       1 reflector.go:147] vendor/k8s.io/client-go/informers/factory.go:150: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://10.140.0.139:6443/api/v1/services?labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=12829624": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:37:22.210579719Z stderr F W0315 18:37:22.210388       1 reflector.go:535] vendor/k8s.io/client-go/informers/factory.go:150: failed to list *v1.EndpointSlice: Get "https://10.140.0.139:6443/apis/discovery.k8s.io/v1/endpointslices?labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=12829679": dial tcp 10.140.0.139:6443: connect: network is unreachable
2024-03-15T18:37:22.210612994Z stderr F E0315 18:37:22.210458       1 reflector.go:147] vendor/k8s.io/client-go/informers/factory.go:150: Failed to watch *v1.EndpointSlice: failed to list *v1.EndpointSlice: Get "https://10.140.0.139:6443/apis/discovery.k8s.io/v1/endpointslices?labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=12829679": dial tcp 10.140.0.139:6443: connect: network is unreachable
